### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by Meaglin** [lukasoppermann/sqlbuddy#1]
Are you still working on this, if yes maybe contact  the original developer to allow existing users to see that there are updates?

**Comment by lukasoppermann** [comment]
Sorry, not really. I am mostly working with migrations and thus avoiding the whole topic of any sqladmin tool.

**Comment by Meaglin** [comment]
Ah, too bad. Sqlbuddy is still my favorite tool for managing databases. It works allot smoother then phpmyadmin.

I hope someday someone will pickup the development of this great tool.

**Comment by lukasoppermann** [comment]
@Meaglin I see this, if you would like to take over the repo I can transfer it.

**Comment by Meaglin** [comment]
Sadly i dont have the time and motivation to maintain it either :(

**Comment by lukasoppermann** [comment]
Ahh, I see, that is indeed sad, but very understandable. 

Maybe somebody will take it up and hopefully take over the main repo as well. Or maybe a group of people.
